apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-build
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      type: string
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable
      securityContext:
        privileged: true   # simplify for now
      script: |
        buildah bud -t $(params.IMAGE) .
        buildah push $(params.IMAGE)
