apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: microservice-pipeline
spec:
  serviceAccountName: buildah-sa
  params:
    - name: repo-url
    - name: image
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: imageTag
      description: The image tag
  workspaces:
    - name: shared-data
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-data
    - name: debug-workspace
      runAfter:
        - clone
      taskRef:
        name: debug-workspace
      workspaces:
        - name: debug
          workspace: shared-data
    - name: build
      runAfter:
        - clone
      taskRef:
        name: buildah-build
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params.image)
        - name: BUILDDIR
          value: workspace/source